osudroid/osu-droid

src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java

Using the system's default locale when formatting strings can result in an improperly formatted string in some languages (for example, `1.20` (float) gets be converted to `1,20` (string)). This will cause mod string to be stored incorrectly in score database and further causes crash when:
- Trying to load scores from local leaderboard
- Importing a replay where the user that exports the replay has this bug
Example screenshot of improperly formatted mod string (device uses Vietnamese language):
Screenshot of exported replay after device switches to English language:

Fix speed multiplier and force AR storing method

---

res/values/options.xml
src/ru/nsu/ccfit/zuev/audio/serviceAudio/BassAudioFunc.java

Fixed bug : When use "enable metronome in speed modify" option, it caps final speed Multiplier at 0.75-1.5

Fixed bug : "enable metronome in speed modify" option caps final speed Multiplier at 0.75-1.5

---

src/com/edlplan/ui/ActivityOverlay.kt

this should fix the `Exception: Fragment already added` error on all fragments/menus including the back button.

Fix crash when menus get called to show twice

---

res/values/options.xml

So better precision is available for the playfield shrink. 90% feels too small for comfort compared to 100%. Or we should allow the user to change the shrink to any integer percentage from 100% to 10% since the touch position clamp was implemented (But I don't know how to do that)

Add 95% and 85% options for Playfield Shrink

---

src/ru/nsu/ccfit/zuev/osu/game/GameScene.java

Flashlight mod icon doesn't appear at the start of a gameplay even when enabled.
Reported by a user in Discord.

Fix flashlight mod not showing when starting gameplay

---

src/ru/nsu/ccfit/zuev/osu/game/Slider.java

Originally reported by @el-dasher, sliders would disappear before they even appear in Hidden mod:
https://user-images.githubusercontent.com/52914632/115642035-728ed900-a344-11eb-995d-6f0ffaa0b83d.mp4
Also made it so that the fade-out duration reflects speed-changing mods properly.

Fix sliders with custom speed multiplier disappearing before active in Hidden mod

---

src/ru/nsu/ccfit/zuev/osu/game/GameScene.java

Just a minor fix.
Retrying a map with storyboard causes a crash. The bug is caused by trying to attach an entity that's already attached to a parent. I've applied a fix by detaching itself prior to attaching to the parent.

Fix storyboard crash upon retrying map

---

res/values/options.xml
src/ru/nsu/ccfit/zuev/osu/MainActivity.java

Fixes issue #95.
On lower background brightness, the image artifacts are more visible. No code is handling the "Use Hardware Dither" in options, so I used the option to toggle this dithering option. Ideally I'd remove the option and permanently apply the fix, but I figured it may cause problems I did not catch. **This fix requires a restart.**
I've tested it myself, but if possible, this requires testing on different devices to check for issues. Please notify me immediately if issues are found.

Fix picture dithering issues

---

README.md
res/values/options.xml
res/xml/options.xml
src/ru/nsu/ccfit/zuev/osu/Config.java
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java

This PR adds `Config.setHideReplayMarquee()` and the option to hide the following in-game elements: combo burst, healthbar(scorebar), combo, accuracy & score counter. Also some grammar fix on the README.

Add hide ingame ui option with minor updates to Config.java and README

---

src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java

With my previous improvement on Auto cursor, it completely breaks at high AR (above AR10, more so above AR11). This fixes it by adjusting the speed (more like the "time" required for the cursor to go from the first note to the next) by modifying the approach rate **used for calculation**.
Since the velocity of the cursor depends on approach rate, forcing AR slightly above AR 10 (something like AR 10.1) speeds up the cursor considerably. I don't find this worth changing, so I left it as it is.
I've only tested it on 2 maps on my AVD, each with 2 difficulties, with DTHR and Force AR tested, so far no issues. If anyone who tests this finds one, let me know.

Implement AR checking for Auto cursor

---

src/ru/nsu/ccfit/zuev/osu/Config.java
src/ru/nsu/ccfit/zuev/osu/MainActivity.java
src/ru/nsu/ccfit/zuev/osu/helper/FileUtils.java

This PR fixes the crashes experienced by users after they update to the new version when they're not running Android Oreo or above.

Fix crashes on devices running below Android 11

---

src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java

This happened because in the pre-release I saw the cursor to be faster than I originally planned.
In my recent Auto cursor fix, I overlooked the millisecond to AR in AR checking. It was supposed to be multiplied by 1000 as the approach rate given by the parameter was in seconds. As such, this PR fixes that issue. It should work properly now.
While I'm at it, I made the cursor faster when AR is below AR 10, as I think some people may find it too slow.

Fix AR checking for Auto cursor

---

res/values/options.xml
res/values/strings.xml
src/ru/nsu/ccfit/zuev/osu/MainScene.java
src/ru/nsu/ccfit/zuev/osu/menu/SettingsMenu.java

Toggling dithering on or off without a restart (closing the game directly from the recents list) may cause a crash on certain devices when closing options; this PR adds a restart dialog when toggling the option.
Pressing "ok" will restart the game, while pressing/swiping back will not restart the game, nor will it crash when closing options (tested this on my phone, which prior to this addition/fix, the crash was easily reproduced), as the change will apply at restart. Toggling back the option to its initial value (let's say, on -> off -> on) won't display the dialog.
While I'm at it, I changed the dithering option's description to be... more descriptive.

Add restart dialog when toggling dither

---

src/ru/nsu/ccfit/zuev/osu/MainScene.java

Basically solves this bug:
By replacing `android.os.Process.killProcess()` with `MainActivity.finish()` in the method `MainScene.exit()` that does pretty much the same but also removes all fragments.
`exit()` is called when the user clicks on **Exit** from the main menu or when the user clicks on the close button from the notification.
To produce that bug in pre-release 3: 
1. Click **Play** and **Settings** at the same time.
2. Close the Settings Menu
3. Open Mod Menu
4. Then minimize the game, and close it from the notification.
6. Now start the game again and you get it.

Fix for fragments still showing after game exit.

---

src/ru/nsu/ccfit/zuev/osu/MainScene.java

Moving OnlinePanel entity detach to update thread to avoid concurrency issues which is the cause of that exception.
"potential" because this doesn't always happen (depends of how fast update thread is running on).

Fix potential indexOutOfBoundsException

---

src/ru/nsu/ccfit/zuev/osu/LibraryManager.java

I erroneously used a `return` instead of a `continue` in one of the loops updating the cache when it detects a new beatmap (when `tracks` in `TrackInfo` is empty), potentially resulting in certain beatmaps to not be imported if the loop hits an unparseable beatmap mid-caching. This PR fixes that issue.

Fix a bug in LibraryManager where a loop may terminate prematurely

---

AndEngine/src/org/anddev/andengine/extension/input/touch/controller/MultiTouchController.java

The game throws an `IllegalArgumentException` when it receives an unknown input event, leading to crashes most noticeable when tapping on the screen with the S-Pen button pressed. This PR solves this issue.

Fix crash when unknown input event is received

---

AndroidManifest.xml

The game launches an `Intent` as part of the updating process. It is currently missing the required permission to install the APK file. This PR fixes the issue by adding the required permission to the manifest.

Add missing permission required for the updater

---

src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java

This PR closes #324.
The way osu!droid handles the movement of the auto cursor is suboptimal (thanks to me :D). This PR fixes it by making the cursor move based only on the time delta between two notes, and purposefully set a minimum time delta to give an impression of "flow aim" in streams. The time delta already scales with AR, so AR is no longer needed to be taken into account.

Improve auto cursor behavior

---

src/ru/nsu/ccfit/zuev/osu/MainActivity.java

This fixes a crash for new installations of osu!droid where a welcome alert is attempted to shown.

Fix crash when trying to show an alert outside UI thread.

---

src/ru/nsu/ccfit/zuev/osu/online/FormDataPostBuilder.java
src/ru/nsu/ccfit/zuev/osu/online/OnlineFileOperator.java
src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
src/ru/nsu/ccfit/zuev/osu/online/PostBuilder.java
src/ru/nsu/ccfit/zuev/osu/online/URLEncodedPostBuilder.java

Pending change server-side.
This is a pre-requisite for dpp integration, and ensures that replays are *always* uploaded, which resolves the issue where a score's replay is outdated or non-existent.

Combine score and replay uploads into one HTTP request

---

res/values/options.xml
res/xml/settings_gameplay.xml
src/ru/nsu/ccfit/zuev/osu/Config.java
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java

Closes #357.
This adds two new settings: display average offset and display unstable rate, allowing finer control and breaking the dependency of some counters.

Decouple FPS and pp counter settings

---

src/com/rian/osu/beatmap/BeatmapConverter.kt
src/com/rian/osu/beatmap/BeatmapProcessor.kt
src/com/rian/osu/beatmap/hitobject/HitCircle.kt
src/com/rian/osu/beatmap/hitobject/HitObject.kt
src/com/rian/osu/beatmap/hitobject/Slider.kt
src/com/rian/osu/beatmap/hitobject/Spinner.kt
src/com/rian/osu/beatmap/hitobject/sliderobject/SliderHitObject.kt
src/com/rian/osu/beatmap/parser/BeatmapParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapHitObjectsParser.kt

To be used to substitute `GameObjectData` in the future, so that the game does not need to reparse the same information. This further reduces the work done in the update thread during gameplay.
More PRs will come as more values are gradually substituted.

Process hitobject combo information

---

src/ru/nsu/ccfit/zuev/osu/game/GameHelper.java
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
src/ru/nsu/ccfit/zuev/osu/game/Slider.java
src/ru/nsu/ccfit/zuev/osu/game/Spinner.java

We have two properties that are very confusingly named:
- `GameScene.timeMultiplier`, which is the rate at which gameplay progresses in terms of time.
- `GameHelper.timeMultiplier`, which is the inverse of `GameScene.timeMultiplier`.
These namings can easily cause mistakes if not paid enough attention. In attempt to remedy this, I have unified them into a single property in `GameHelper.speedMultiplier`, which denotes the rate at which gameplay progresses in terms of time.

Unify time multiplier application

---

src/ru/nsu/ccfit/zuev/osu/game/GameObject.java
src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
src/ru/nsu/ccfit/zuev/osu/game/Slider.java

Currently, circles and sliders have a period during which the object cannot be hit even though it has started their lifetime (that is, it is considered an active object within `GameScene`). The period for both objects are different:
- For circles, the period starts from when the circle spawns until the approach circle is halfway into the circle. This is problematic as it means that AR imposes an additional hit window that can be stricter than the hit window imposed by OD. For example, if the player plays a beatmap with AR10 (450ms approach time) and OD0 (100ms for great, 200ms for good, 300ms for meh), the most lenient hit offset is 225ms due to the hit window imposed by AR, even though the most lenient hit offset in terms of OD is 300ms.
- For sliders, the period starts from when the …

Impose maximum hit range restriction to circles and sliders

---

src/com/edlplan/ui/fragment/PropsMenuFragment.kt
src/com/reco1l/osu/data/BeatmapCollections.kt
src/com/reco1l/osu/data/BeatmapOptions.kt
src/com/reco1l/osu/data/Database.kt
src/com/reco1l/osu/data/Scores.kt

Score table migration was giving troubles with keeping old data as backup in case the process fails or it's aborted, so I decided to change the migration process.
The new process will follow this path:
* First of all check if the old database file exists so we can start the migration.
* Iterate per each row and check if it was already migrated to the new system skipping those that had been.
* Once the entire process ends successfully we can proceed with renaming the file so next time it won't trigger the migration again.

Improve old database system migration

---

res/drawable/rounded_half_bottom.xml
res/drawable/rounded_half_left.xml
res/drawable/rounded_half_right.xml
res/drawable/rounded_half_top.xml
res/drawable/rounded_rect.xml
res/layout/mod_customization_fragment.xml
res/layout/settings_preference_input.xml
res/layout/settings_preference_input_bottom.xml
src/com/edlplan/ui/fragment/InGameSettingMenu.kt
src/com/edlplan/ui/fragment/PropsMenuFragment.kt
src/com/reco1l/osu/data/BeatmapOptions.kt
src/com/reco1l/osu/data/BeatmapSets.kt
src/com/reco1l/osu/data/Beatmaps.kt
src/com/reco1l/osu/data/BlockArea.kt
src/com/reco1l/osu/data/Database.kt
src/com/reco1l/osu/data/Scores.kt
src/com/reco1l/osu/graphics/Modifiers.kt
src/com/reco1l/osu/ui/BlockAreaFragment.kt
src/com/reco1l/osu/ui/SettingsFragment.kt
src/ru/nsu/ccfit/zuev/osu/BeatmapProperties.java
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java

[Fixed](https://github.com/osudroid/osu-droid/pull/406/commits/238d799ca351e7edb51688f1fc3dc5e9c6a6236a)
[Fixed](https://github.com/osudroid/osu-droid/commit/c56442d0b848eb0d8acfeea2d9c0a1defc776e16)
[Fixed](https://github.com/osudroid/osu-droid/pull/406/commits/115816c3afe434b59936b74d49ccdf8b9ddccc4e)
[Fixed](https://github.com/osudroid/osu-droid/pull/406/commits/42e2c4a1bc1a03e345ee7622a49ee9748e2be48c)
[Fixed](https://github.com/osudroid/osu-droid/pull/406/commits/dd4cd086746481d2044920d9c462e819feb5cbee)
[Fixed](https://github.com/osudroid/osu-droid/pull/406/commits/3f3f324c99d5077531b4b5827fe764f203a9c944)
[Fixed](https://github.com/osudroid/osu-droid/pull/406/commits/7836ade34ec07a594b0a1a1e5f5a62f9fceac29e)
[Fixed](https://github.com/osudroid/osu-droid/pull/406/commits/b3a2d13c0644 …

Fix bugs related to latest pull requests

---

res/values/options.xml
res/values/strings.xml
res/xml/settings_general.xml
src/ru/nsu/ccfit/zuev/osu/Config.java
src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
src/ru/nsu/ccfit/zuev/osu/scoring/BeatmapLeaderboardScoringMode.java

This only works for global beatmap leaderboard in song selection. Players can switch between score and pp in main menu options.
To make this work for local scores, the pp values of them will need to be calculated, which can be expensive. Another option is to calculate the pp value of the score during database migration (and store it inside the table), but this is a bit more involved due to slower migration time, rebalance handling, etc., and as such is more suitable for an upcoming PR if needed.

Add pp for global beatmap leaderboard in song selection

---

src/com/reco1l/osu/DifficultyCalculation.kt
src/com/reco1l/osu/data/Scores.kt
src/com/reco1l/osu/graphics/AnimatedSprite.kt
src/com/reco1l/osu/graphics/Modifiers.kt
src/com/reco1l/osu/multiplayer/RoomScene.kt
src/ru/nsu/ccfit/zuev/osu/game/FollowTrack.java
src/ru/nsu/ccfit/zuev/osu/game/GameObject.java
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
src/ru/nsu/ccfit/zuev/osu/game/Slider.java
src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java
src/ru/nsu/ccfit/zuev/osu/menu/LoadingScreen.java
src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java

* Animated sprites fails to retrieve textures when the frame count is 1.
[Fixed](https://github.com/osudroid/osu-droid/commit/ee8c4a476bb8223f16901de65507e59c0d167319)
* Local leaderboard is sorted by insert date rather than score in the song menu.
[Fixed](https://github.com/osudroid/osu-droid/pull/410/commits/498900e2dffb79e50a57a6329352d8a661c22f27)
* Hit circles can potentially get stuck on screen if they're never hit in some maps (e.g. Der Wald by Rocker [Aspire difficulty]).
[Fixed](https://github.com/osudroid/osu-droid/pull/410/commits/70441a4e12f9092c96253d04ef4f47eb44802016)
* Song's menu buttons do not get affected by skin layout configurations.
[Fixed](https://github.com/osudroid/osu-droid/pull/410/commits/56c30974b95e414ccc18006143efe2c73e3b12a9)
* When the beatmap background …

Fix regressions from past pull request

---

src/com/rian/osu/beatmap/Beatmap.kt
src/com/rian/osu/beatmap/BeatmapConverter.kt
src/com/rian/osu/beatmap/BeatmapProcessor.kt
src/com/rian/osu/beatmap/parser/BeatmapParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapColorParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapControlPointsParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapDifficultyParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapEventsParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapGeneralParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapHitObjectsParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapKeyValueSectionParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapMetadataParser.kt
src/com/rian/osu/beatmap/parser/sections/BeatmapSectionParser.kt
src/com/rian/osu/difficulty/BeatmapDifficultyCalculator.kt
src/com/rian/osu/difficulty/calculator/DifficultyCalculator.kt
src/com/rian/osu/difficulty/calculator/DroidDifficultyCalculator.kt
src/com/rian/osu/difficulty/calculator/StandardDifficultyCalculator.kt

A step towards solving #408, given that functions from `Execution` do not provide a `CoroutineScope` to the running function.
This PR adds support for coroutine job cancellation to beatmap parsing and difficulty calculation operations.

Add support for coroutine cancellation in beatmap parsing and difficulty calculation

---

src/com/reco1l/osu/DifficultyCalculation.kt
src/com/reco1l/osu/data/Beatmaps.kt

This PR is an example of working implementation of #416.

Use coroutine in background difficulty calculation

---

andnext_markdown/src/main/java/club/andnext/markdown/MarkdownWebView.java
res/layout/dialog_progress.xml
res/values/styles.xml
src/com/edlplan/ui/fragment/BaseFragment.kt
src/com/edlplan/ui/fragment/MarkdownFragment.java
src/com/reco1l/framework/net/FileRequest.kt
src/com/reco1l/osu/UpdateManager.kt
src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
src/com/reco1l/osu/beatmaplisting/BeatmapListing.kt
src/com/reco1l/osu/multiplayer/LobbyRoomList.kt
src/com/reco1l/osu/ui/Dialog.kt
src/com/reco1l/osu/ui/ListDialog.kt
src/com/reco1l/osu/ui/ProgressDialog.kt
src/com/reco1l/osu/ui/PromptDialog.kt
src/ru/nsu/ccfit/zuev/osu/Config.java
src/ru/nsu/ccfit/zuev/osu/MainActivity.java
src/ru/nsu/ccfit/zuev/osu/ToastLogger.java
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java

- Fixed an issue where the game could potentially crash when running the game over animation with video background is enabled.
- `UpdateManager` will now use game's dialogs instead of Android native.
- `UpdateManager` will no longer cache update builds, forcing re-download just in case.
- Fixed a bug where the changelog is not showing after updating, as well the `UpdateManager` will use local changelog.

Corrections after 1.8.1 release

---

AndEngine/src/org/anddev/andengine/entity/scene/CameraScene.java

Fixes the GL_STACK_UNDERFLOW error on glPopMatrix due to pushing and popping with different matrix modes.

Fix GL_STACK_UNDERFLOW on glPopMatrix

---

src/com/rian/osu/difficulty/DifficultyHitObject.kt
src/com/rian/osu/difficulty/DroidDifficultyHitObject.kt
src/com/rian/osu/difficulty/calculator/DroidDifficultyCalculator.kt
src/com/rian/osu/difficulty/evaluators/DroidFlashlightEvaluator.kt
src/com/rian/osu/difficulty/evaluators/DroidVisualEvaluator.kt
src/com/rian/osu/difficulty/evaluators/StandardFlashlightEvaluator.kt
src/com/rian/osu/difficulty/skills/DroidFlashlight.kt
src/com/rian/osu/difficulty/skills/DroidVisual.kt
src/com/rian/osu/difficulty/skills/StandardFlashlight.kt

This adds difficulty calculation for the Traceable mod in osu!droid difficulty calculation. Unlike the osu!standard counterpart, no performance calculation is necessary as all difficulty assessments are done in difficulty calculation.

Add osu!droid difficulty calculation for Traceable mod

---

src/com/reco1l/osu/hud/elements/HUDNotesPerSecondCounter.kt
src/com/reco1l/osu/hud/elements/HUDStatisticsCounters.kt
src/com/reco1l/osu/hud/elements/HUDTapsPerSecondCounter.kt

This abstracts `HUDStatisticCounter` so that it can also be used by other statistic-like counters that do not rely on `StatisticV2`, allowing the reuse of auto-anchor logic that was introduced in #504.

Abstractify `HUDStatisticCounter`

---

src/com/reco1l/osu/hud/HUDElement.kt

`GameplayHUD` calls `IEntity.detachSelf()` when replacing the current `HUDElement`s with the saved ones. However, the editor overlay and anchor line of an `HUDElement` are attached to `GameplayHUD` and not the `HUDElement` itself. This causes the editor overlay and anchor line to not be detached during the operation, leading to `GameplayHUD` childrens growing continuously as `setSkinData` gets called (or from the user's side, each time they discard changes).
I could choose to change the detaching operation within `GameplayHUD` to call `HUDElement.remove()` instead, but that is not a fool-proof solution.

Fix `HUDElement`s not detaching editor overlay and anchor line when being detached

---

src/com/rian/osu/mods/ModTimeRamp.kt
src/com/rian/osu/utils/ModUtils.kt
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java

This PR adds support for dynamically adjusting speed multiplier in gameplay via `ModTimeRamp`.
Of note, I only PR'd this because I do not need to touch `GameMod` (which will be replaced in the upcoming mods storage rework). I have the implementation of `ModWindUp` ready from this PR, but I will not PR (and not recommend anyone) to test it until the rework is done and merged.

Add support for dynamic speed multiplier adjustment in gameplay via `ModTimeRamp`

---

res/values/strings_temporary_for_locals.xml
src/com/edlplan/replay/OsuDroidReplayPack.java
src/com/osudroid/ui/v2/modmenu/ModMenu.kt
src/com/rian/osu/beatmap/Beatmap.kt
src/com/rian/osu/beatmap/BeatmapProcessor.kt
src/com/rian/osu/beatmap/hitobject/HitObject.kt
src/com/rian/osu/beatmap/hitobject/Slider.kt
src/com/rian/osu/difficulty/calculator/DroidDifficultyCalculator.kt
src/com/rian/osu/mods/IModApplicableToBeatmap.kt
src/com/rian/osu/mods/Mod.kt
src/com/rian/osu/mods/ModHidden.kt
src/com/rian/osu/mods/ModReplayV6.kt
src/com/rian/osu/mods/ModTimeRamp.kt
src/com/rian/osu/mods/ModType.kt
src/com/rian/osu/utils/ModHashMap.kt
src/com/rian/osu/utils/ModUtils.kt
src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
tests/test/kotlin/com/rian/osu/difficulty/calculator/DroidDifficultyCalculatorTest.kt
tests/test/kotlin/com/rian/osu/difficulty/calculator/StandardDifficultyCalculatorTest.kt
tests/test/kotlin/com/rian/osu/mods/ModReplayV6Test.kt
tests/test/kotlin/com/rian/osu/utils/ModUtilsTest.kt

This will be the first round of fixes for the current stacking behavior.
In short, the current stacking behavior is wrong for a multitude of reasons. Some of them are that:
- It does not stack sliders
- It is based on the delta time of two objects instead of approach rate, the factor that *actually* affects readability
- Stacking can still apply even when two objects are not in the same position
More importantly, or perhaps the primary driving factor of this change, is because stack offset calculation depends on the device's screen resolution under the following logic:
https://github.com/osudroid/osu-droid/blob/fdb145b5b198bd0c5060898b83800bd043c42391/src/ru/nsu/ccfit/zuev/osu/Config.java#L253-L269
Which is used when calculating `HitObject.gameplayScale`: …

Partially match stacking behavior with osu!stable

---

src/com/osudroid/ui/v2/modmenu/ModCustomizationMenu.kt
src/com/osudroid/ui/v2/modmenu/ModSettingCheckbox.kt
src/com/osudroid/ui/v2/modmenu/ModSettingComponent.kt
src/com/osudroid/ui/v2/modmenu/ModSettingSlider.kt
src/com/osudroid/ui/v2/modmenu/ModSettingTextInput.kt
src/com/reco1l/andengine/ui/TextInput.kt
src/com/reco1l/andengine/ui/form/FormInput.kt
src/com/rian/osu/mods/ModDifficultyAdjust.kt
src/com/rian/osu/mods/ModRandom.kt
src/com/rian/osu/mods/ModSetting.kt

This PR adds support for `ModSetting`s that rely on manual user input, such as `ModRandom.seed`.
Of note, this also fixes the following problems with the current `TextInput` implementation (oversights on my review):
- The caret's position is not updated when the value of a `TextInput` is changed via external means (i.e., a `FormControl`'s reset button). This causes an IOOBE when the user attempts to write again.
- When deleting a character, the caret now only moves if its position is after the deleted character. This behavior is in line with many text inputs.
I've also changed the behavior of `minValue` and `maxValue` in `ModSetting` to cap the value instead of throwing.

Add support for text input based `ModSetting`

---

src/com/osudroid/ui/v2/modmenu/ModMenuPresetsSection.kt
src/com/osudroid/ui/v2/modmenu/ModPresetsForm.kt
src/com/reco1l/andengine/ExtendedEngine.kt
src/com/reco1l/andengine/Initializers.kt
src/com/reco1l/andengine/UIScene.kt
src/com/reco1l/andengine/buffered/BufferSharingMode.kt
src/com/reco1l/andengine/buffered/CompoundBuffer.kt
src/com/reco1l/andengine/buffered/IBuffer.kt
src/com/reco1l/andengine/buffered/UIBufferedComponent.kt
src/com/reco1l/andengine/component/Components.kt
src/com/reco1l/andengine/component/UIComponent.kt
src/com/reco1l/andengine/container/UIFlexContainer.kt
src/com/reco1l/andengine/container/UILinearContainer.kt
src/com/reco1l/andengine/container/UIScrollableContainer.kt
src/com/reco1l/andengine/shape/UIBox.kt
src/com/reco1l/andengine/shape/UICircle.kt
src/com/reco1l/andengine/shape/UILine.kt
src/com/reco1l/andengine/shape/UITriangle.kt
src/com/reco1l/andengine/sprite/UISprite.kt
src/com/reco1l/andengine/text/UIText.kt
src/com/reco1l/andengine/text/UITextureText.kt
src/com/reco1l/andengine/ui/UIButton.kt
src/com/reco1l/andengine/ui/UIModal.kt
src/ru/nsu/ccfit/zuev/audio/serviceAudio/BassAudioFunc.java
src/ru/nsu/ccfit/zuev/audio/serviceAudio/SongService.java
src/ru/nsu/ccfit/zuev/osu/MainScene.java
tests/test/kotlin/com/reco1l/andengine/UIComponentTest.kt
tests/test/kotlin/com/reco1l/andengine/UIDummyComponent.kt
tests/test/kotlin/com/reco1l/andengine/UIFlexContainerTest.kt

* Introduced `UIFlexContainer`, works similarly as a flex-box from CSS (lacks features but for what we have now it's enough).
* `UIText` now measures its content size when the flag `Content` is set, it also preserves lines and line widths to reutilize on each invalidation.
* `UIBufferedComponent` no longer uses varargs when updating the buffer data.
* Introduced a way to determine when a buffer is shared and how should it be handled.
* Fixed a bug where the scrolling on a `UIScrollableContainer` was reduced in velocity incorrectly.
* Fixed content size measurement being wrong when a container has only one child in some layouts.
* Fixed potential NPE when trying to compute component size with Scene's `Camera` being `null`.
* Fixed theme not being propagated properly along entities.
* Fixed …

More corrections and improvements to the framework
