osudroid/osu-droid

- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
修复了一些图(比如859515)点击note时会因为音效数组越界而闪退的bug
> fixed a hitsound bug

- src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
长度低于50ms的转盘自动转
负长度转盘自动转
负长度转盘测试用map:496199
> fixed spinner bug

- .typo-ci.yml
- AndroidManifest.xml
- build.gradle
- res/values/strings.xml
- src/ru/nsu/ccfit/zuev/audio/serviceAudio/SongService.java
- src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
- src/ru/nsu/ccfit/zuev/osu/MainActivity.java
- src/ru/nsu/ccfit/zuev/osu/MainScene.java
- src/ru/nsu/ccfit/zuev/osu/SkinManager.java
- src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
~~TODO: Need someone to test 5d3e754 with a disposable sdcard~~
> Add minor changes

- res/values/strings.xml
- src/ru/nsu/ccfit/zuev/osu/MainScene.java
- src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
- src/ru/nsu/ccfit/zuev/osu/online/OnlinePanel.java
- src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
- src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
~~TODO: Need to add code to check if it's still trying logging in~~
TODO: Need to be able to actually log in to test if the checks are working when already logged in
> Add user panel

- src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
Song library version should increse after star rate recalculating.
Solving #32
> Increse song library version to 3.4

- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/ru/nsu/ccfit/zuev/osu/helper/sql/DBOpenHelper.java
Fixed bug:Stacked sliders (sliderheads) abnormal when use CalculateSliderPathInGameStart
Increse the library version number from 6 to 7
> Fixed some bugs of PR #26

- src/ru/nsu/ccfit/zuev/osu/MainActivity.java
- src/ru/nsu/ccfit/zuev/osu/MainScene.java
- src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
- src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
fixed skin load bug in some android 10 (temporary)
> Store extra mod string in replay

- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
This bug has been reported in #41, however the video provided doesn't properly show bug reproduction, so I made another one: https://youtu.be/MBN-FoGD6vo
> Fix failsound not stopping when device back button is pressed

- src/ru/nsu/ccfit/zuev/osu/helper/DifficultyReCalculator.java
Port pp calculation changes from:
- https://github.com/ppy/osu-performance/pull/125
- https://github.com/ppy/osu-performance/pull/127
- https://github.com/ppy/osu-performance/pull/128
- https://github.com/ppy/osu-performance/pull/129
> Port Xexxar and StanR's pp calculation changes

- build.gradle
- src/com/edlplan/ui/fragment/BuildTypeNoticeFragment.kt
- src/ru/nsu/ccfit/zuev/audio/serviceAudio/SaveServiceObject.java
Specify build flavor (from where you get the app)
> Add build flavor

- src/ru/nsu/ccfit/zuev/osu/MainActivity.java
added `Config.isHideNaviBar` on line #692 at `MainActivity.java`
sorry for the typo
> Fix minor navbar issue

- src/ru/nsu/ccfit/zuev/osu/Config.java
- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
Previously I had applied a fix, but I reverted the fix because I expected an options UI revamp. Now I re-added the fix. It should theoretically fix the "bug" (more of no code handling the option), if it doesn't work as expected please let me know.
> Avatar loading without Wifi fix

- src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
> Fix main score information string

- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/test/tpdifficulty/tp/AiModtpDifficulty.java
> Fixed bug: Difficulty calculation breaks down at very high CS

- src/ru/nsu/ccfit/zuev/osu/Config.java
- src/ru/nsu/ccfit/zuev/osu/MainActivity.java
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Originally, I only wanted to fix replay directory for custom main directory, however I noticed that many user-configurable settings involving directories are not checked (and loaded) properly, so here I am.
> Fix directory loading

- assets/app/changelog.md
- src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
- src/ru/nsu/ccfit/zuev/osu/game/Slider.java
> Fix custom beatmap skin hitcircle not overriding slider start/end circle

- res/values/strings.xml
- src/com/edlplan/ui/fragment/MapInfoFragment.java
- src/ru/nsu/ccfit/zuev/osu/OSUParser.java
- src/ru/nsu/ccfit/zuev/osu/TrackInfo.java
- src/ru/nsu/ccfit/zuev/osu/game/Slider.java
- src/ru/nsu/ccfit/zuev/osu/helper/DifficultyReCalculator.java
- src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
- src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
- src/test/tpdifficulty/hitobject/HitObjectType.java
- src/test/tpdifficulty/hitobject/Slider.java
- src/test/tpdifficulty/tp/tpHitObject.java
- Fixed #78 
- Fixed a false NaN comparison
- Refactor many parts of code
> Fix bugs and refactor code

- src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
Fixed bug: animated hit100k/hit300g/hit300k is not working
> Fixed bug: Animated 100k,300k,300g is unable

- res/values/strings.xml
- src/com/edlplan/ui/fragment/MapInfoFragment.java
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/ru/nsu/ccfit/zuev/osu/game/Slider.java
- src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
- src/ru/nsu/ccfit/zuev/osu/helper/DifficultyReCalculator.java
- src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
- src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
- src/test/tpdifficulty/tp/AiModtpDifficulty.java
- src/test/tpdifficulty/tp/tpHitObject.java
Can save failed replay
Can save replay in offline
Fixed a bug that star calculate no calculate DT/NC/speed modify
move the pp display (score scene) to left-bottom
> Save failed replay And Fixed a bug

- src/com/edlplan/osu/support/slider/SliderBody2D.java
- src/ru/nsu/ccfit/zuev/osu/game/Slider.java
Fades out a slider's body, border, and hint if Hidden mod is used.
https://user-images.githubusercontent.com/52914632/114761903-4fd05380-9d8b-11eb-9736-240d82425eb5.mp4
> Add slider fade out for Hidden mod

- src/ru/nsu/ccfit/zuev/osu/menu/FilterMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/IScrollBarListener.java
- src/ru/nsu/ccfit/zuev/osu/menu/LoadingScreen.java
- src/ru/nsu/ccfit/zuev/osu/menu/MenuItem.java
- src/ru/nsu/ccfit/zuev/osu/menu/MenuItemBackground.java
- src/ru/nsu/ccfit/zuev/osu/menu/MenuItemListener.java
- src/ru/nsu/ccfit/zuev/osu/menu/MenuItemTrack.java
- src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
- src/ru/nsu/ccfit/zuev/osu/menu/ScrollBar.java
- src/ru/nsu/ccfit/zuev/osu/menu/SettingsMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/SongMenuPool.java
- src/ru/nsu/ccfit/zuev/osu/menu/SplashScene.java
Basically i followed my IDE to try to mitigate as many warns as possible in the menu classes, also simplified a piece of code in ModMenu.java, till now i didn't found any weird behaviours.
> Refactor song menu

- .github/workflows/android.yml
- README.md
Updates action/setup-java from the actions file to use v2 and the Adopt OpenJDK Hotspot distribution and minor changes to the README.
> Update actions/setup-java and minor README changes

- res/values/options.xml
- res/xml/options.xml
- src/ru/nsu/ccfit/zuev/osu/Config.java
- src/ru/nsu/ccfit/zuev/osu/game/SongProgressBar.java
Just something minor that was suggested by a user in Discord.
Allows the player to hide song progress bar on the bottom of the screen during gameplay.
> Add song progress bar toggle

- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Like osu!std does, just added a if statement checking if the mod hidden is enabled or not.
_(sorry for the PR clone)_
> Burst effect disabled when hidden mod is enabled.

- src/ru/nsu/ccfit/zuev/audio/serviceAudio/NotifyPlayer.java
- src/ru/nsu/ccfit/zuev/audio/serviceAudio/SaveServiceObject.java
- src/ru/nsu/ccfit/zuev/audio/serviceAudio/SongService.java
- src/ru/nsu/ccfit/zuev/osu/MainScene.java
This doesn't fully fix it, but the user will be able to swipe the player away, so no big deal.
> Fix music player not disappearing when quitting the game from multitask menu

- res/layout/fragment_build_type_notice.xml
- src/com/edlplan/ui/fragment/BuildTypeNoticeFragment.kt
- src/ru/nsu/ccfit/zuev/osu/MainActivity.java
The idea was from mr. Chadcivev
> Add last osu!droid release disclaimer

- res/xml/options.xml
- src/ru/nsu/ccfit/zuev/osu/Config.java
Closes #216
Why that range ? Because of higher would make the SeekBar uncontrollable.
> Set offset range to -250 to 250

- src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
> Make PF compatible with RX and AP

- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
`ScoreBoard.java`'s async implementation is half-baked, creating a lot of concurrency problems and issues with read/write. This PR rewrites the class to better support asynchronous operations.
> Refactor scoreboard and fix asynchronous scoreboard loading

- src/ru/nsu/ccfit/zuev/osu/game/Slider.java
and a reformatting of the file to make it more readable
> Fix slider follow circle tick animation to only play when there is no other animation playing

- src/com/reco1l/legacy/data/MultiplayerConverter.kt
- src/com/reco1l/legacy/ui/multiplayer/StatisticSelector.kt
- src/ru/nsu/ccfit/zuev/osu/game/DuringGameScoreBoard.java
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoardItem.java
- src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Requires #274 because Im bad at Git
> Implement HP recovery system

- src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
- src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
This tries to alleviate the effects specified in #276
> Rework leaderboard loading logic in SongMenu

- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
This is client-side, backend needs support for this.
> Support personal best score in global leaderboard

- res/layout/fragment_in_game_option.xml
- src/com/edlplan/ui/fragment/InGameSettingMenu.java
- src/com/reco1l/api/ibancho/data/Room.kt
- src/com/reco1l/legacy/data/MultiplayerConverter.kt
- src/com/reco1l/legacy/ui/entity/InGameLeaderboard.kt
- src/com/reco1l/legacy/ui/multiplayer/LobbyRoomList.kt
- src/com/reco1l/legacy/ui/multiplayer/RoomMods.kt
- src/com/reco1l/legacy/ui/multiplayer/RoomPlayerList.kt
- src/com/reco1l/legacy/ui/multiplayer/RoomScene.kt
- src/ru/nsu/ccfit/zuev/osu/game/cursor/flashlight/FlashLightEntity.java
- src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
Recommended to review per commit
> 1.7.1 Fixes from here to there

- .github/workflows/android.yml
- .github/workflows/gradle-wrapper-validation.yml
- AndEngine/AndroidManifest.xml
- AndEngine/build.gradle
- AndroidManifest.xml
- LibBASS/build.gradle
- LibBASS/src/main/AndroidManifest.xml
- andnext_markdown/build.gradle
- andnext_markdown/src/main/AndroidManifest.xml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- src/com/edlplan/framework/support/batch/AbstractBatch.java
- src/com/edlplan/osu/support/timing/TimingPoint.java
- src/com/edlplan/ui/InputDialog.java
- src/com/edlplan/ui/fragment/FilterMenuFragment.kt
- src/com/edlplan/ui/fragment/InGameSettingMenu.kt
- src/com/edlplan/ui/fragment/SettingsFragment.kt
- src/com/reco1l/legacy/ui/multiplayer/RoomPlayerList.kt
- src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Seeing that the current Gradle and AGP version is very out of date, it would be beneficial to update the Gradle and AGP version to 8.2 and 8.2.2 respectively for a while. All dependencies are updated to their latest versions and have already been tested to work.
> Update Gradle, AGP, and dependencies to their latest versions

- src/com/edlplan/framework/support/osb/StoryboardSprite.java
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Reimplement Overlay layer and support video.
> Fix storyboard

- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
> Fix touch events being recorded with update thread clock

- src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
- src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
> Fix PP being calculated when team statistics are selected on Multiplayer

- src/com/reco1l/andengine/sprite/AnimatedSprite.kt
- src/com/reco1l/framework/Bitmaps.kt
- src/com/reco1l/osu/BuildUtils.kt
- src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
* Animated sprites now reset properly when they're reused in `GameEffect`
* FPS counter dummy entity will now be attached to the HUD rather than the scene.
* Added shape preservation for no texture mode (Debug utils)
> Corrections related to previous PRs

- build.gradle
- src/com/edlplan/ui/ImportReplayActivity.java
- src/com/edlplan/ui/fragment/FavoriteManagerFragment.java
- src/com/edlplan/ui/fragment/FilterMenuFragment.kt
- src/com/edlplan/ui/fragment/ScoreMenuFragment.java
- src/com/reco1l/osu/AccessibilityDetector.kt
- src/com/reco1l/osu/UpdateManager.kt
- src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
- src/com/reco1l/osu/ui/SettingsFragment.kt
- src/com/reco1l/osu/ui/entity/MainMenu.kt
- src/com/rian/osu/beatmap/parser/BeatmapParser.kt
- src/ru/nsu/ccfit/zuev/osu/AppException.java
- src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
- src/ru/nsu/ccfit/zuev/osu/MainActivity.java
- src/ru/nsu/ccfit/zuev/osu/MainScene.java
- src/ru/nsu/ccfit/zuev/osu/RankedStatus.java
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/ru/nsu/ccfit/zuev/osu/helper/FileUtils.java
- src/ru/nsu/ccfit/zuev/osu/helper/StringTable.java
- src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
- src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
- src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
- src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
- src/ru/nsu/ccfit/zuev/osu/online/OnlinePanel.java
- src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
- src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
* Starting from this PR the game is no longer compatible with Android versions lower than 7 (Nougat).
* Namespace for the external resources repository was changed to `com.osudroid.resources`.
* StringTable functions that use `StringBuilder` are now synchronized.
> Synchronize StringTable, Change external osu!droid resources namespace, Set min SDK version to 24

- res/layout/beatmap_downloader_filters.xml
- res/layout/beatmap_downloader_fragment.xml
- res/layout/dropdown_fragment.xml
- src/com/reco1l/osu/beatmaplisting/BeatmapListing.kt
- src/com/reco1l/osu/beatmaplisting/BeatmapMirrorModels.kt
- src/com/reco1l/osu/beatmaplisting/mirrors/Catboy.kt
- src/com/reco1l/osu/beatmaplisting/mirrors/OsuDirect.kt
- src/com/reco1l/osu/ui/Dialog.kt
- src/com/reco1l/osu/ui/ListDialog.kt
- src/ru/nsu/ccfit/zuev/osu/RankedStatus.java
> Introduce beatmap listing filters

- src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
> fix download speed unit

- src/com/reco1l/osu/hud/GameplayHUD.kt
- src/com/reco1l/osu/hud/HUDElement.kt
- src/com/reco1l/osu/hud/IGameplayEvents.kt
- src/com/reco1l/osu/hud/editor/HUDElementSelector.kt
- src/com/reco1l/osu/hud/elements/HUDNotesPerSecondCounter.kt
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Adds a notes per second counter as an HUD element in gameplay.
> Add notes per second counter

- src/com/reco1l/osu/hud/GameplayHUD.kt
- src/com/reco1l/osu/hud/HUDElement.kt
- src/com/reco1l/osu/hud/IGameplayEvents.kt
- src/com/reco1l/osu/hud/editor/HUDElementSelector.kt
- src/com/reco1l/osu/hud/elements/HUDTapsPerSecondCounter.kt
- src/ru/nsu/ccfit/zuev/osu/game/GameObjectListener.java
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
- src/ru/nsu/ccfit/zuev/osu/game/GameplayModernSpinner.java
- src/ru/nsu/ccfit/zuev/osu/game/GameplaySpinner.java
Adds a taps per second counter as an HUD element in gameplay.
Unfortunately, this is not as clean as #500, mainly due to the fact that Auto cursor click handling is all over the place.
> Add taps per second counter

- src/com/reco1l/osu/hud/HUDElement.kt
- src/com/reco1l/osu/hud/elements/HUDBPMCounter.kt
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Adds a BPM counter as an HUD element in gameplay. Also scales with speed multiplier.
---
> Add BPM counter

- build.gradle
- res/values/strings_temporary_for_locals.xml
- res/xml/settings_input.xml
- src/com/reco1l/osu/hud/GameplayHUD.kt
- src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
> Move temporary locals

- src/com/reco1l/andengine/shape/BezelOutline.kt
- src/com/reco1l/andengine/ui/Badge.kt
- src/com/reco1l/andengine/ui/Button.kt
- src/com/reco1l/andengine/ui/Checkbox.kt
- src/com/reco1l/andengine/ui/Control.kt
- src/com/reco1l/andengine/ui/Modal.kt
- src/com/reco1l/andengine/ui/Slider.kt
- src/com/reco1l/andengine/ui/Theme.kt
- src/com/reco1l/andengine/ui/form/FormCheckbox.kt
- src/com/reco1l/andengine/ui/form/FormControl.kt
- src/com/reco1l/andengine/ui/form/FormSlider.kt
> Implement UI components based on `ExtendedEntity`
